export const FETCH_BOOKS = "FETCH_BOOKS";
export const NEW_BOOKS = "NEW_BOOKS";
export const FETCH_BOOK_SERIES = "FETCH_BOOK_SERIES";
export const NEW_BOOK_SERIES = "NEW_BOOK_SERIES";
export const FETCH_BOOK_SERIES_INDEX = "FETCH_BOOK_SERIES_INDEX";
export const FETCH_CHAPTERS = "FETCH_CHAPTERS";
export const NEW_CHAPTERS = "NEW_CHAPTERS";