json.array! @all,
            :name,
            :race,
            :subrace,
            :background,
            :alignment,
            :level,
            :strength,
            :dexterity,
            :constitution,
            :intelligence,
            :wisdom,
            :charisma,
            :experience,
            :player_name,
            :character_class